backend: 
  name: git-gateway
  branch: main
media_folder: "src/assets/images"
public_folder: "/assets/images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "src/blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "layout", name: "layout", widget: "hidden", default: "layouts/post.html"}
      - { label: "title", name: "title", widget: "string", required: true }
      - { label: "date", name: "date", widget: "datetime", format: "LLLL" }
      - {
          label: "updated",
          name: "updated",
          widget: "datetime",
          format: "LLLL",
          required: false,
          default: "",
        }
      - { label: "tags", name: "tags", widget: "list" }
      - { label: "body", name: "body", widget: "markdown" }